In [1]:
import gba
import numpy as np
import matplotlib.pyplot as plt

In [2]:
model = gba.read_ods_model(path="../gba/data/models", name="L3rev2")

In [3]:
model.find_initial_solution(condition_id="15", rhs_factor=50.0)

coucou RMM
coucou RMM
coucou RMM


❯ Info Model is consistent with mu = 0.06822646196856656.

In [4]:
mu_vec = []
for conc in np.arange(1, 0.1, -0.01):
    model.conditions[1,14] = conc
    model.set_condition(condition_id="15")
    converged = model.find_optimum(verbose=False)
    if converged:
        mu_vec.append(model.mu)
        model.set_f0(model.f.copy())
    else:
        print("Model inconsistent for conc =", conc)
        print(model.f)
        model.calculate()
        model.check_model_consistency()
        print(model.consistent)
        print(model.b)
        print(model.c)
        print(model.p)
        break

libc++abi: terminating due to uncaught exception of type std::runtime_error: > Error: The initial solution f0 is not consistent


⚠ Warning Solver failed.

Model inconsistent for conc = 0.7799999999999998
[1.       0.98886  0.952213]
True
[0.01114  0.036647 0.952213]
[  3.7876   12.45998 323.75242]
[151.90402879  65.37100979 106.47738142]


In [5]:
model.adjust_concentrations

False